name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  APP_ENV: DEV

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Clean
        run: mvn clean

      - name: Compile
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Deploy
        run: echo "Deploying Application"
